### ISSUE TITLE
Drag and drop multiple selections in the main diagram

### ISSUE THREAD

**Issue by chaser-at-its** [dbflute-session/erflute#23]
メインダイアグラムでテーブルを複数選択してドラッグアンドドロップできないのは、何か理由があるのでしょうか。

もし特になければ、できるようにしてプルリクエストしようと思います。

**Comment by jflute** [comment]
No reason about User Interface.
Only human resource problem exists.
(Originally, ERMaster-b cannot do it)

There is the man who improves ERFlute.
But he is very young (of programming skill)
so difficult tickets are pending...
https://www.slideshare.net/YoshioKajikuri/2oss

Welcome to your pull request.

**Comment by jflute** [comment]
By the way, there is the mail thread of ERFlute (in DBFlute ML).
You can get ERFlute information.
https://groups.google.com/forum/#!msg/dbflute/uAOLFGNGfAU/_6VBJgFMAgAJ

ちなみに、DBFluteのMLの中にERFluteのメールスレッドがあります。
ERFluteのお知らせなど見れますので、ぜひ参考にしてみてください。
Issueにするほとでもないくらいの質問とかあれば、気軽にこちらでもOKです。

**Comment by chaser-at-its** [comment]
このプルリクエストのリリースを確認しました。クローズします。
